spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdatabase
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true